hydra:
  run:
    dir: ./experiments/${name}/${hydra.job.override_dirname}/seed=${seed}
  sweep:
    dir: ./experiments/${name}/${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        item_sep: '_'
        exclude_keys:
          - seed
          - name
          - posterior_predictive_num_samples
          - model
          - sdvi.save_metrics_every_n
          - sdvi.num_parallel_processes
          - sdvi.exclusive_kl_num_particles

defaults:
  # - launcher: slurm
  - model: gaussian_mixture_model
  - resource_allocation: successive_halving
  # - override hydra/launcher: submitit_slurm

# constraint_fn_name: split_at_0

sdvi:
  _target_: models.pyro_extensions.infer.SDVI
  guide_class_name: MeanFieldNormal
  learning_rate: 0.01
  find_slp_samples: 1000
  forward_kl_iter: 1000
  forward_kl_num_particles: 1
  initial_num_iterations: 100
  num_iterations_per_step: 100
  num_steps: 10
  exclusive_kl_num_particles: 1
  elbo_estimate_num_particles: 1
  iwae_num_inner: null
  use_iwae_for_weights: False
  num_parallel_processes: 10
  save_metrics_every_n: 10


init_loc_fn: init_to_mean

posterior_predictive_num_samples: 100

name: test
seed: 0